// Generated by: main
// TypeWriter: set
// Directive: +gen on GameObject

package game

// Set is a modification of https://github.com/deckarep/golang-set
// The MIT License (MIT)
// Copyright (c) 2013 Ralph Caraveo (deckarep@gmail.com)

// The primary type that represents a set
type GameObjectSet map[GameObject]struct{}

// Creates and returns a reference to an empty set.
func NewGameObjectSet(a ...GameObject) GameObjectSet {
	s := make(GameObjectSet)
	for _, i := range a {
		s.Add(i)
	}
	return s
}

// ToSlice returns the elements of the current set as a slice
func (set GameObjectSet) ToSlice() []GameObject {
	var s []GameObject
	for v := range set {
		s = append(s, v)
	}
	return s
}

// Adds an item to the current set if it doesn't already exist in the set.
func (set GameObjectSet) Add(i GameObject) bool {
	_, found := set[i]
	set[i] = struct{}{}
	return !found //False if it existed already
}

// Determines if a given item is already in the set.
func (set GameObjectSet) Contains(i GameObject) bool {
	_, found := set[i]
	return found
}

// Determines if the given items are all in the set
func (set GameObjectSet) ContainsAll(i ...GameObject) bool {
	for _, v := range i {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

// Determines if every item in the other set is in this set.
func (set GameObjectSet) IsSubset(other GameObjectSet) bool {
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Determines if every item of this set is in the other set.
func (set GameObjectSet) IsSuperset(other GameObjectSet) bool {
	return other.IsSubset(set)
}

// Returns a new set with all items in both sets.
func (set GameObjectSet) Union(other GameObjectSet) GameObjectSet {
	unionedSet := NewGameObjectSet()

	for elem := range set {
		unionedSet.Add(elem)
	}
	for elem := range other {
		unionedSet.Add(elem)
	}
	return unionedSet
}

// Returns a new set with items that exist only in both sets.
func (set GameObjectSet) Intersect(other GameObjectSet) GameObjectSet {
	intersection := NewGameObjectSet()
	// loop over smaller set
	if set.Cardinality() < other.Cardinality() {
		for elem := range set {
			if other.Contains(elem) {
				intersection.Add(elem)
			}
		}
	} else {
		for elem := range other {
			if set.Contains(elem) {
				intersection.Add(elem)
			}
		}
	}
	return intersection
}

// Returns a new set with items in the current set but not in the other set
func (set GameObjectSet) Difference(other GameObjectSet) GameObjectSet {
	differencedSet := NewGameObjectSet()
	for elem := range set {
		if !other.Contains(elem) {
			differencedSet.Add(elem)
		}
	}
	return differencedSet
}

// Returns a new set with items in the current set or the other set but not in both.
func (set GameObjectSet) SymmetricDifference(other GameObjectSet) GameObjectSet {
	aDiff := set.Difference(other)
	bDiff := other.Difference(set)
	return aDiff.Union(bDiff)
}

// Clears the entire set to be the empty set.
func (set *GameObjectSet) Clear() {
	*set = make(GameObjectSet)
}

// Allows the removal of a single item in the set.
func (set GameObjectSet) Remove(i GameObject) {
	delete(set, i)
}

// Cardinality returns how many items are currently in the set.
func (set GameObjectSet) Cardinality() int {
	return len(set)
}

// Iter() returns a channel of type GameObject that you can range over.
func (set GameObjectSet) Iter() <-chan GameObject {
	ch := make(chan GameObject)
	go func() {
		for elem := range set {
			ch <- elem
		}
		close(ch)
	}()

	return ch
}

// Equal determines if two sets are equal to each other.
// If they both are the same size and have the same items they are considered equal.
// Order of items is not relevent for sets to be equal.
func (set GameObjectSet) Equal(other GameObjectSet) bool {
	if set.Cardinality() != other.Cardinality() {
		return false
	}
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Returns a clone of the set.
// Does NOT clone the underlying elements.
func (set GameObjectSet) Clone() GameObjectSet {
	clonedSet := NewGameObjectSet()
	for elem := range set {
		clonedSet.Add(elem)
	}
	return clonedSet
}
